


class Commands:
        StartCommand = 'start'
        ReStartCommand = 'restart'
        UpTime = 'time'
        Log = 'log'
        Stats = 'stats'
        Authorize = 'auth'
        UnAuthorize = 'unauth'
        AddSudo = 'addsudo'
        RemoveSudo = 'rmsudo'
        ChangeConfig = 'changeconfigs'
        LC = 'leech'
        ZipLC = 'zipleech'
        CancelCommand = 'cancel'
        CancelAllCommand= 'cancelall'
        UnzipLC = 'unzipleech'
        MC = 'mirror'
        ZipMC = 'zipmirror'
        UnzipMC = 'unzipmirror'
        StatusCommand = 'status'
        UserSetCommand = 'usetting'
        YtdlLC = 'ytdlleech'
        YtdlZipLC = 'ytdlzipleech'
        YtdlCommand = 'ytdl'
        YtdlZipCommand = 'ytdlzip'
        ResetConfig = 'resetconfig'
        BotPriveteFiles = 'privatefiles'